  # Uncomment the next line to define a global platform for your project
  platform :ios, '9.0'

target 'MapAppMobile' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  #use_frameworks!

  #pod 'Yoga', :path => '../node_modules/react-native/ReactCommon/yoga/Yoga.podspec'
  #pod 'React', path: '../node_modules/react-native', :subspecs => [
  #  'Core',
  #  'RCTActionSheet',
  #  'RCTAnimation',
  #  'RCTGeolocation',
  #  'RCTImage',
  #  'RCTLinkingIOS',
  #  'RCTNetwork',
  #  'RCTSettings',
  #  'RCTText',
  #  'RCTVibration',
  #  'RCTWebSocket'
  #]

  pod 'GoogleMaps'  # <~~ remove this line if you do not want to support GoogleMaps on iOS
  #pod 'react-native-maps', path: '../node_modules/react-native-maps/react-native-maps.podspec'
  #pod 'react-native-google-maps', path: '../node_modules/react-native-maps/react-native-google-maps.podspec'  # <~~ if you need GoogleMaps support on iOS

  end


  post_install do |installer|
  installer.pods_project.targets.each do |target|
    if target.name == "react-native-google-maps"
      target.build_configurations.each do |config|
        config.build_settings['CLANG_ENABLE_MODULES'] = 'No'
      end
    end
  end

  target 'MapAppMobile-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MapAppMobileTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'MapAppMobile-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for MapAppMobile-tvOS

  target 'MapAppMobile-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
